filebeat.inputs:
- type: file
  enabled: true
  paths:
    - /var/log/{{COMPONENT}}.log

output.elasticsearch:
  index: "{{COMPONENT}}"
  hosts: ["elasticsearch.roboshop.internal:9200"]

# --------------------------
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

output.elasticsearch.index: "{{COMPONENT}}"
setup.template.name: "{{COMPONENT}}"
setup.template.pattern: "{{COMPONENT}}"
