- name: Copy rsyslog config
  ansible.builtin.template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/roboshop.conf

- name: Restart Rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

